### ISSUE TITLE
Rename use_packs to packs and packs to packs-specification

### ISSUE THREAD

**Issue by alexevanczuk** [rubyatscale/.github#5]
Might want to start a discussion about this in use_packs.

Related: https://github.com/rubyatscale/use_packs/issues/18

`packs` could be the single entry point for development considerations for the packs ecosystem. `packs-specification` is what you rely on to just get the spec for adding new features to packs.

**Comment by franzliedke** [comment]
It seems like this was done with https://github.com/rubyatscale/packs/pull/96, is that correct?

It confused me a bit, as we were only requiring `packs` (the specification) in our project and the latest Dependabot PR essentially makes us switch to the new `packs` (previously `use_packs`). 😵‍💫

**Comment by alexevanczuk** [comment]
Ah oof @franzliedke , sorry for that. If you switch from `packs` to `packs-specification`, does the error go away?

**Comment by franzliedke** [comment]
@alexevanczuk Yes, all fine, that was the (easy) fix. I guess the changelog could have been a bit more explicit about this breaking (?) change.

> Rename gem to packs

I was missing the context about the previous name. 😅 But I also get that our case of only using `packs-specification` might be a rather rare one.

Thanks for this awesome ecosystem! 😍 

This ticket can probably be closed.

**Comment by alexevanczuk** [comment]
I hear what you're saying – definitely room to have clearer documentation and guidance around the breaking change – appreciate you bringing it up!

This was a big conceptual change in how we were thinking of naming/branding things and hoping it doesn't have to happen again 🙏🏼 . Really appreciate your patience and understanding. I'm hoping that at some point it'd be possible to release a 1.0.0 version that's a bit more stable for folks.

Will close this for now. Please continue to file issues with any and all feedback!
